apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-hotrod
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: example-hotrod
  template:
    metadata:
      labels:
        name: example-hotrod
    spec:
      containers:
      - args:
        - all
        env:
        - name: JAEGER_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        image: jaegertracing/example-hotrod:1.45
        name: example-hotrod
        ports:
        - containerPort: 8080
          name: http0
          protocol: TCP
        - containerPort: 8081
          name: http1
          protocol: TCP
        - containerPort: 8082
          name: http2
          protocol: TCP
        - containerPort: 8083
          name: http3
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  annotation:
    metallb.universe.tf/ip-allocated-from-pool: main
  name: example-hotrod
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  - port: 8081
    protocol: TCP
    targetPort: 8081
  - port: 8082
    protocol: TCP
    targetPort: 8082
  - port: 8083
    protocol: TCP
    targetPort: 8083
  selector:
    name: example-hotrod
  type: LoadBalancer