apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  strategy: allinone
  storage:
    type: memory 
    options: 
      memory: 
        max-traces: 1000
  ingress:
    enabled: false 
  agent:
    strategy: DaemonSet 

